site_name: Fetch.AI Developer Documentation
site_url: https://docs.fetch.ai/
site_description: Everything you need to know about Fetch.AI. 
#repo_url: https://github.com/fetchai // commented out to remove edit option
#repo_name: 'GitHub'
site_author: katharine.murphy@fetch.ai

theme:
  name: 'material'
  logo:
    icon: code
  custom_dir: custom_theme/
  favicon: '/assets/images/favicon.ico'
  feature:
    tabs: true  


nav:


  - Getting Started:
    - Versions: './getting-started/versions.md'
    - Install the Fetch.AI Ledger: 
      - "MacOS": './getting-started/installation-mac.md'
      - "Ubuntu": './getting-started/installation-ubuntu.md'
      - "Redhat": './getting-started/installation-redhat.md'
    - Python Ledger API: './getting-started/python-api-install.md'
    - Open Economic Framework: './getting-started/oef-install.md'



  - Open Economic Framework:
    - Welcome:
      - "What is the OEF?": 'oef/index.md'
    - The Basics:
      - "Running a node" : 'oef/running-a-node.md'
      - "Get the SDK" : 'oef/sdk.md'
      - "Get a public key" : 'oef/public-key.md'
    - How It Works:
      - "Registering" : 'oef/registering.md'
      - "Advertising" : 'oef/advertising.md'
      - "Searching" : 'oef/searching.md'
      - "Negotiating" : 'oef/negotiating.md'
    - Python API:
      - "Python API" : 'oef/python-API.md'



  - Etch Language:
    - Welcome:
        - "What's etch?": 'etch-language/index.md'
        - 'Getting started': 'etch-language/getstarted.md'
        - 'Debugging': 'etch-language/debug.md'
        - 'Release notes': 'etch-language/release-notes.md'
    - The Basics:
        - 'Syntax': 'etch-language/syntax.md'
        - 'Variables': 'etch-language/variables.md'
        - 'Operators': 'etch-language/operators.md'
        - 'Logical operators': 'etch-language/logic.md'
        - 'Control flow': 'etch-language/control-flow.md'
        - 'Strings': 'etch-language/strings.md'
        - 'Arrays': 'etch-language/arrays.md'
        - 'Functions': 'etch-language/functions.md'
        - 'Regex': 'etch-language/regex.md'
        - 'Error checking': 'etch-language/error-checking.md'
    - Fetch Ledger Types:
        - 'States': 'etch-language/states.md'
        - 'Sharded State': 'etch-language/sharded-state.md'
        - 'Addresses': 'etch-language/addresses.md'
        - 'Cryptographic functions': 'etch-language/crypto.md'
    - Machine Learning:
        - 'Maths libraries and functions': 'etch-language/maths-libs.md'
        - 'Machine learning and AI': 'etch-language/ML-AI.md'
    - Extending Etch:
        - 'Extending etch in C++': 'etch-language/extending-etch.md'
    - Examples: 
        - 'Fetch logo': 'etch-language/examples/fetch-logo.md'
        - 'Mandelbrot': 'etch-language/examples/mandelbrot.md'
        - 'Searching algorithms': 'etch-language/examples/searching-algorithms.md'
        - 'Sorting algorithms': 'etch-language/examples/sorting-algorithms.md'



  - Smart Contracts:
    - 'Introduction': 'smart-contracts/smart-contract-intro.md'
    - 'Data types': 'smart-contracts/data-types.md'
    - 'Memory': 'smart-contracts/memory.md'
#    - 'Transactions': 'smart-contracts/transactions.md'
    - 'Smart contracts': 'smart-contracts/smart-contracts.md'
#    - 'Synergetic contracts': 'smart-contracts/synergetic.md'
    - 'Executing smart contract code': 'smart-contracts/executing-smart-contract-code.md'
    - 'Tutorials':
      - "Hello world smart contract": 'smart-contracts/submitting_contract.md'
      - "Create FET-20 contract": 'smart-contracts/erc20.md'
      - "Create FET-721 contract": 'smart-contracts/erc721.md'
#    - 'Deploying an agent': 'smart-contracts/prediction_agent.md'



# Options
extra:
  logo: 'assets/images/favicon.ico'

markdown_extensions:
  - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css